-- UNIDADMEDIDA
INSERT INTO UNIDADMEDIDA (DENOMINACION) VALUES ('Unidad');
INSERT INTO UNIDADMEDIDA (DENOMINACION) VALUES ('Kg');
INSERT INTO UNIDADMEDIDA (DENOMINACION) VALUES ('Litro');

-- CATEGORIA
INSERT INTO CATEGORIA (DENOMINACION, ESINSUMO) VALUES ('Bebidas', FALSE);
INSERT INTO CATEGORIA (DENOMINACION, ESINSUMO) VALUES ('Comidas', FALSE);
INSERT INTO CATEGORIA (DENOMINACION, ESINSUMO) VALUES ('Insumos Cocina', TRUE);

-- ARTICULOS (productos e insumos)
INSERT INTO ARTICULO (CODIGO, DENOMINACION, PRECIOVENTA, UNIDADMEDIDA_FK, CATEGORIA_FK) VALUES ('A001', 'Coca Cola 500ml', 800, 1, 1);
INSERT INTO ARTICULO (CODIGO, DENOMINACION, PRECIOVENTA, UNIDADMEDIDA_FK, CATEGORIA_FK) VALUES ('A002', 'Hamburguesa Completa', 2500, 1, 2);
INSERT INTO ARTICULO (CODIGO, DENOMINACION, PRECIOVENTA, UNIDADMEDIDA_FK, CATEGORIA_FK) VALUES ('A003', 'Pan de Hamburguesa', 200, 1, 3);
INSERT INTO ARTICULO (CODIGO, DENOMINACION, PRECIOVENTA, UNIDADMEDIDA_FK, CATEGORIA_FK) VALUES ('A004', 'Medallón de Carne', 800, 1, 3);
INSERT INTO ARTICULO (CODIGO, DENOMINACION, PRECIOVENTA, UNIDADMEDIDA_FK, CATEGORIA_FK) VALUES ('A005', 'Queso Cheddar', 900, 1, 3);

-- ARTICULOINSUMO
INSERT INTO ARTICULOINSUMO (ID, ESPARAELABORAR, PRECIOCOMPRA, STOCKACTUAL, STOCKMAXIMO) VALUES (3, TRUE, 100, 100, 500);
INSERT INTO ARTICULOINSUMO (ID, ESPARAELABORAR, PRECIOCOMPRA, STOCKACTUAL, STOCKMAXIMO) VALUES (4, TRUE, 350, 80, 400);
INSERT INTO ARTICULOINSUMO (ID, ESPARAELABORAR, PRECIOCOMPRA, STOCKACTUAL, STOCKMAXIMO) VALUES (5, TRUE, 500, 60, 300);

-- ARTICULOMANUFACTURADO (producto final)
INSERT INTO ARTICULOMANUFACTURADO (ID, DESCRIPCION, PREPARACION, TIEMPOESTIMADOMINUTOS) VALUES (2, 'Hamburguesa Completa con papas', 'Armar pan, carne, queso y aderezos', 15);

-- ARTICULOMANUFACTURADODETALLE (detalle de receta)
INSERT INTO ARTICULOMANUFACTURADODETALLE (CANTIDAD, ARTICULOINSUMO_FK, ARTICULOMANUFACTURADO_FK) VALUES (1, 3, 2);
INSERT INTO ARTICULOMANUFACTURADODETALLE (CANTIDAD, ARTICULOINSUMO_FK, ARTICULOMANUFACTURADO_FK) VALUES (1, 4, 2);
INSERT INTO ARTICULOMANUFACTURADODETALLE (CANTIDAD, ARTICULOINSUMO_FK, ARTICULOMANUFACTURADO_FK) VALUES (1, 5, 2);

-- CLIENTES
INSERT INTO CLIENTE (CUIT, RAZONSOCIAL) VALUES ('20-12345678-9', 'Juan Pérez');
INSERT INTO CLIENTE (CUIT, RAZONSOCIAL) VALUES ('27-98765432-1', 'Comidas Mendoza SRL');

-- FACTURAS
INSERT INTO FACTURA (FECHAALTA, FECHACOMPROBANTE, NROCOMPROBANTE, PUNTOVENTA, TOTAL, CLIENTEID_FK) VALUES (CURRENT_DATE(), CURRENT_DATE(), 1001, 1, 3300, 1);

-- FACTURADETALLE
INSERT INTO FACTURADETALLE (CANTIDAD, SUBTOTAL, ARTICULOID_FK, FACTURAID_FK) VALUES (1, 2500, 2, 1);
INSERT INTO FACTURADETALLE (CANTIDAD, SUBTOTAL, ARTICULOID_FK, FACTURAID_FK) VALUES (1, 800, 1, 1);

-- IMAGENES
INSERT INTO IMAGEN (DENOMINACION, ARTICULO_FK) VALUES ('/imagenes/coca.png', 1);
INSERT INTO IMAGEN (DENOMINACION, ARTICULO_FK) VALUES ('/imagenes/hamburguesa.png', 2);

-- Datos adicionales para Ejercicio 3 y 4
-- Más facturas para diferentes clientes
INSERT INTO FACTURA (FECHAALTA, FECHACOMPROBANTE, NROCOMPROBANTE, PUNTOVENTA, TOTAL, CLIENTEID_FK) VALUES (CURRENT_DATE(), CURRENT_DATE(), 1002, 1, 3300, 1);
INSERT INTO FACTURA (FECHAALTA, FECHACOMPROBANTE, NROCOMPROBANTE, PUNTOVENTA, TOTAL, CLIENTEID_FK) VALUES (CURRENT_DATE(), CURRENT_DATE(), 1003, 1, 1600, 2);
INSERT INTO FACTURA (FECHAALTA, FECHACOMPROBANTE, NROCOMPROBANTE, PUNTOVENTA, TOTAL, CLIENTEID_FK) VALUES (CURRENT_DATE(), CURRENT_DATE(), 1004, 1, 5800, 1);
INSERT INTO FACTURA (FECHAALTA, FECHACOMPROBANTE, NROCOMPROBANTE, PUNTOVENTA, TOTAL, CLIENTEID_FK) VALUES (CURRENT_DATE(), CURRENT_DATE(), 1005, 1, 2500, 2);

-- Más detalles de facturas para ver artículos más vendidos
-- Factura 2 (cliente 1)
INSERT INTO FACTURADETALLE (CANTIDAD, SUBTOTAL, ARTICULOID_FK, FACTURAID_FK) VALUES (2, 1600, 1, 2);
INSERT INTO FACTURADETALLE (CANTIDAD, SUBTOTAL, ARTICULOID_FK, FACTURAID_FK) VALUES (1, 2500, 2, 2);

-- Factura 3 (cliente 2)
INSERT INTO FACTURADETALLE (CANTIDAD, SUBTOTAL, ARTICULOID_FK, FACTURAID_FK) VALUES (2, 1600, 1, 3);

-- Factura 4 (cliente 1)
INSERT INTO FACTURADETALLE (CANTIDAD, SUBTOTAL, ARTICULOID_FK, FACTURAID_FK) VALUES (3, 2400, 1, 4);
INSERT INTO FACTURADETALLE (CANTIDAD, SUBTOTAL, ARTICULOID_FK, FACTURAID_FK) VALUES (2, 5000, 2, 4);

-- Factura 5 (cliente 2)
INSERT INTO FACTURADETALLE (CANTIDAD, SUBTOTAL, ARTICULOID_FK, FACTURAID_FK) VALUES (1, 2500, 2, 5);

